django/Balungu/lab1/mysite/mysite/blog/urls.py
from . import views

from django.urls import path

app_name = "blog"

urlpatterns = [

    path('', views.PostList.as_view(), name='home'),

    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("member", views.member, name="member"),
    path("password_reset", views.password_reset_request, name="password_reset"),


]

django/Balungu/lab1/mysite/mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User 

STATUS = ((0,"Draft"),(1,"Publish")) 

class Post(models.Model): 

    title = models.CharField(max_length=200, unique=True) 

    slug = models.SlugField(max_length=200, unique=True) 

    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts') 

    updated_on = models.DateTimeField(auto_now= True) 
    content = models.TextField() 

    created_on = models.DateTimeField(auto_now_add=True) 
    status = models.IntegerField(choices=STATUS, default=0) 

 

    class Meta: 

        ordering = ['-created_on'] 

 

    def __str__(self): 

        return self.title 


# Create your models here.

django/Balungu/lab1/mysite/mysite/blog/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User


# Create your forms here.


class NewUserForm(UserCreationForm):

    email = forms.EmailField(required=True)

    class Meta:

        model = User

        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):

        user = super(NewUserForm, self).save(commit=False)

        user.email = self.cleaned_data['email']

        if commit:

            user.save()

        return user

django/Balungu/lab1/mysite/mysite/blog/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import generic

from .models import Post
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes


class PostList(generic.ListView):

    queryset = Post.objects.filter(status=1).order_by('-created_on')

    template_name = 'index.html'


class PostDetail(generic.DetailView):

    model = Post

    template_name = 'post_detail.html'


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("blog:member")
        messages.error(
            request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="blog/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("blog:member")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="blog/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("blog:home")


def member(request):
    return render(request, "blog/member.html")


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "blog/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="blog/password/password_reset.html", context={"password_reset_form": password_reset_form})

django/Balungu/lab1/mysite/mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html> 


<html> 

 

<head> 

 <title>HTGAWM Blog</title> 

 <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet"> 

 <meta name="google" content="notranslate" /> 

<meta name="viewport" content="width=device-width, initial-scale=1" /> 

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
 

</head> 

 

 <body> 
    
 <style> 

 body { 

font-family: "Roboto", sans-serif; 

font-size: 17px; 
background: url('{% static "img/bg.jpg" %}')  no-repeat center center fixed;
    background-size: cover;
 
 
 
 
 
 

} 
footer{
    
    position: fixed;
    height: 50px;
    background: rgb(2,0,36);
    background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(218,236,227,1) 0%, rgba(244,177,190,1) 88%, rgba(0,212,255,1) 100%);
    bottom: 0px;
    left: 0px;
    right: 0px;
    margin-bottom: 0px;
}

 .shadow { 

box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1); 

 } 

.btn-danger { 

 color: #fff; 

background-color: #f00000; 
border-color: #dc281e; 

 } 

.masthead { 

background: rgb(2,0,36);
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(244,177,190,1) 35%, rgba(0,212,255,1) 100%);

 height: auto; 

 padding-bottom: 15px; 

 box-shadow: 0 16px 48px #E3E7EB; 

 padding-top: 10px; } 
</style> 

 

 

 <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav"> 

 <div class="container-fluid"> 

<a class="navbar-brand" href="{% url 'blog:home' %}">HTGAWM Blog</a> 

<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" 

aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"> 

 <span class="navbar-toggler-icon"></span> 

 </button> 

 <div class="collapse navbar-collapse" id="navbarResponsive"> 

 <ul class="navbar-nav ml-auto"> 

 <li class="nav-item text-black"> 

<a class="nav-link text-black font-weight-bold" href="#">About</a> 

 </li> 

 <li class="nav-item text-black"> 

 <a class="nav-link text-black font-weight-bold" href="#">Policy</a> 

 </li> 

 <li class="nav-item text-black"> 

 <a class="nav-link text-black font-weight-bold" href="#">Contact</a> 

 </li> 
 <li class="nav-item text-black"> 

    <a class="nav-link text-black font-weight-bold" href="/login">Login</a> 
   
    </li> 

 </ul> 

</div> 

</div> 

 </nav> 

{% block content %} 

<!-- Content Goes here --> 

{% endblock content %} 


 <!-- Footer --> 

 <footer class="py-3 bg-grey"> 

 <p class="m-0 text-dark text-center ">Copyright &copy; HTGAWM</p> 

 </footer> 

 </body> 

</html> 

django/Balungu/lab1/mysite/mysite/blog/templates/blog/index.html
{% extends "blog/base.html" %} 

{% block content %} 

<style> 

 body { 

 font-family: "Roboto", sans-serif; 

 font-size: 18px; 

 background-color: #fdfdfd; 

 } 

 

 .head_text { 

 color: white; 

 } 

 

 .card { 

box-shadow: 0 16px 48px #E3E7EB; 

} 

</style> 

 

<header class="masthead"> 

 <div class="overlay"></div> 

 <div class="container"> 

 <div class="row"> 

 <div class=" col-md-8 col-md-10 mx-auto"> 

 <div class="site-heading"> 

 <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3> 

<p class="text-light">We Love TV Shows As much as you do..! &nbsp 

 </p> 

</div> 

 </div> 

 </div> 

</div> 

</header> 

<div class="container"> 

 <div class="row"> 

<!-- Blog Entries Column --> 

 <div class="col-md-8 mt-3 left"> 

 {% for post in post_list %} 

 <div class="card mb-4"> 

 <div class="card-body"> 

 <h2 class="card-title">{{ post.title }}</h2> 

 <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p> 

 <p class="card-text">{{post.content|slice:":200" }}</p> 
 <a href="{% url 'blog:post_detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a> 

 </div> 

 </div> 

 {% endfor %} 

 </div> 

 {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %} 

 </div> 

</div> 

{%endblock%} 

django/Balungu/lab1/mysite/mysite/blog/templates/blog/login.html
{% extends "blog/base.html" %} 

 

{% block content %} 

 

{% load crispy_forms_tags %} 

 

<!--Login-->  

<div class="container py-5"> 

 <h1 style ="color: white; font-weight: 700;">Login</h1> 
<form method="POST" style="color: aliceblue;"> 

{% csrf_token %} 

{{ login_form|crispy }} 
<br>
 <button class="btn btn-primary" type="submit">Login</button> 

</form> 
<br>
<p class="text-center" style="color: aquamarine;">Don't have an account? <a href="/register">Create an account</a>.</p> 
<br>
<p class="text-center" style="color: aqua;"><a href="/password_reset">Forgot password?</a></p>

</div> 

 

{% endblock %} 

django/Balungu/lab1/mysite/mysite/blog/templates/blog/member.html
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 

    crossorigin="anonymous" /> 
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet"> 
 
    <style>
     body {
        background: rgb(2,0,36);
        background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(244,177,190,1) 35%, rgba(0,212,255,1) 100%);
       
        
      } 
 
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm  bg-light">
        
        
        <a class="navbar-brand" href="#">HTGAWM Blog </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle = "collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
    
    
    <div class="collapse navbar-collapse " id="navbarText">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Welcome, {{user.username}}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-item" href="/login">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
    </nav>
  </body>
</html>

django/Balungu/lab1/mysite/mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block content %} 

 

<div class="container"> 

 <div class="row"> 

 <div class="col-md-8 card mb-4 mt-3 left top"> 

<div class="card-body"> 

 <h1>{% block title %} {{ object.title }} {% endblock title %}</h1> 

<p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p> 

<p class="card-text ">{{ object.content | safe }}</p> 

</div> 

</div> 

 {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %} 

</div> 

</div> 

 

{% endblock content %} 

django/Balungu/lab1/mysite/mysite/blog/templates/blog/register.html
{% extends "blog/base.html" %} 

 

{% block content %}  

 

{% load crispy_forms_tags %} 

 

<!--Register-->  

<div class="container py-5"> 

 <h1 style="color: white; font-weight: 700;">Register</h1> 
 <form method="POST" style="color: beige;"> 

{% csrf_token %} 

 {{ register_form|crispy }}

 <button class="btn btn-primary" type="submit">Register</button> 

</form> 
<br>
<p class="text-center" style="color: aquamarine;">If you already have an account, <a href="/login">login</a> instead.</p> 

</div> 

 

{% endblock %} 

django/Balungu/lab1/mysite/mysite/blog/templates/blog/sidebar.html
{% block sidebar %} 

 

<style> 

 .card{ 

 box-shadow: 0 16px 48px #E3E7EB; 

 } 

 

</style> 
<!-- Sidebar Widgets Column --> 

<div class="col-md-4 float-right "> 

    <div class="card my-4"> 
    
     <h5 class="card-header">About Us</h5> 
    
 <div class="card-body"> 
    
     <p class="card-text"> This awesome blog is dedicated to the amazing TV show "HOW TO GET AWAY WITH MURDER". The show had six seasons that aired from September of 2014 to May of 2020.</p> 
    
     <a href="https://kinopoisk.ru/series/804876/" 
    
    class="btn btn-danger">Catch up!</a> 
    
    </div> 
    
    </div> 
    
    </div> 
    
     
    
    {% endblock sidebar %} 